export global Palette {
    in-out property <brush> glass-background: @linear-gradient(180deg, #111115dd 0%, #16161add 100%);
    in-out property <brush> glass-border: @linear-gradient(135deg, #ffffff25 0%, #ffffff0c 100%);
    in-out property <color> shadow-color: #000000aa;
    in-out property <color> text-primary: #ffffff;
    in-out property <color> text-secondary: #aaaaaa;
    in-out property <length> topbar-height: 50px;
}