[package]
name = "AuroraSteamWrapper"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared" }

slint = { workspace = true }
open = { workspace = true }
dirs = { workspace = true }

[build-dependencies]
slint-build = { workspace = true }
image = { workspace = true }

[target.'cfg(target_os = "windows")'.build-dependencies]
winresource = { workspace = true }
