use image::imageops::FilterType;
use std::fs;
use std::path::Path;

fn main() {
    let pairs = [
        ("../../production/assets", "../../production/assets/processed"),
        ("../../production/icons",  "../../production/icons/processed"),
    ];

    for (source, processed) in pairs.map(|(s, p)| (Path::new(s), Path::new(p))) {
        if source.exists() {
            let _ = fs::remove_dir_all(processed);
            fs::create_dir_all(processed).unwrap();
            process_directory(source, source, processed);
        }
    }

    generate_languages_slint();
    slint_build::compile("../../frontend/main.slint").unwrap();

    #[cfg(target_os = "windows")]
    {
        let mut res = winresource::WindowsResource::new();
        res.set_manifest_file("main.manifest");
        res.compile().unwrap();
    }
}

fn generate_languages_slint() {
    const JSON_PATH: &str = "../../production/Langs/lang-codes.json";
    const SLINT_OUT:  &str = "../../frontend/languages.slint";

    println!("cargo:rerun-if-changed={JSON_PATH}");

    let json = fs::read_to_string(JSON_PATH)
        .unwrap_or_else(|e| panic!("Could not read {JSON_PATH}: {e}"));

    let langs: Vec<serde_json::Value> = serde_json::from_str(&json)
        .unwrap_or_else(|e| panic!("Invalid JSON in {JSON_PATH}: {e}"));

    let names = langs
        .iter()
        .map(|l| {
            let name = l["name"].as_str()
                .unwrap_or_else(|| panic!("Missing \"name\" field in {JSON_PATH}"));
            format!("        \"{name}\"")
        })
        .collect::<Vec<_>>()
        .join(",\n");

    let slint = format!(
        "// AUTO-GENERATED BY BUILD.RS - DO NOT EDIT BY HAND!\n\
         // Edit production/Langs/lang-codes.json instead!\n\
         \n\
         export global Languages {{\n\
             out property <[string]> names: [\n\
         {names},\n\
             ];\n\
         }}\n"
    );

    fs::write(SLINT_OUT, slint)
        .unwrap_or_else(|e| panic!("Could not write {SLINT_OUT}: {e}"));
}

fn process_directory(root_source: &Path, current_source: &Path, target_base: &Path) {
    for entry in fs::read_dir(current_source).unwrap() {
        let entry = entry.unwrap();
        let path = entry.path();
        if path == target_base {
            continue;
        }

        let relative = path.strip_prefix(root_source).unwrap();
        let dest_path = target_base.join(relative);

        if path.is_dir() {
            fs::create_dir_all(&dest_path).unwrap();
            process_directory(root_source, &path, target_base);
        } else if path.is_file() {
            if let Some(extension) = path.extension().and_then(|os| os.to_str()) {
                let ext_lower = extension.to_lowercase();
                if ext_lower == "png" || ext_lower == "jpg" || ext_lower == "jpeg" {
                    let file_name = path.file_name().and_then(|os| os.to_str()).unwrap_or("");
                    if file_name.contains("background") {
                        fs::copy(&path, &dest_path).unwrap();
                        continue;
                    }

                    if let Ok(img) = image::open(&path) {
                        let scaled = img.resize(64, 64, FilterType::Lanczos3);
                        scaled
                            .save(&dest_path)
                            .expect("Failed to save downsampled asset");
                    } else {
                        fs::copy(&path, &dest_path).unwrap();
                    }
                }
            }
        }
    }
}