use image::imageops::FilterType;
use std::fs;
use std::path::Path;

fn main() {
    let pairs = [
        (
            "../../production/assets",
            "../../production/assets/processed",
        ),
        ("../../production/icons", "../../production/icons/processed"),
    ];

    for (source, processed) in pairs.map(|(s, p)| (Path::new(s), Path::new(p))) {
        if source.exists() {
            let _ = fs::remove_dir_all(processed);
            fs::create_dir_all(processed).unwrap();
            process_directory(source, source, processed);
        }
    }

    generate_languages_slint();
    generate_translations_slint();
    generate_character_icons();
    slint_build::compile("../../frontend/main.slint").unwrap();

    #[cfg(target_os = "windows")]
    {
        let mut res = winresource::WindowsResource::new();
        res.set_icon("../../production/icons/logo.ico");
        res.set_manifest_file("main.manifest");
        res.compile().unwrap();
    }
}

fn generate_languages_slint() {
    const JSON_PATH: &str = "../../production/Langs/lang-codes.json";
    const SLINT_OUT: &str = "../../frontend/languages.slint";

    println!("cargo:rerun-if-changed={JSON_PATH}");

    let json =
        fs::read_to_string(JSON_PATH).unwrap_or_else(|e| panic!("Could not read {JSON_PATH}: {e}"));

    let langs: Vec<serde_json::Value> =
        serde_json::from_str(&json).unwrap_or_else(|e| panic!("Invalid JSON in {JSON_PATH}: {e}"));

    let names = langs
        .iter()
        .map(|l| {
            let name = l["name"]
                .as_str()
                .unwrap_or_else(|| panic!("Missing \"name\" field in {JSON_PATH}"));
            format!("        \"{name}\"")
        })
        .collect::<Vec<_>>()
        .join(",\n");

    let slint = format!(
        "// AUTO-GENERATED BY BUILD.RS - DO NOT EDIT BY HAND!\n\
         // Edit production/Langs/lang-codes.json instead!\n\
         \n\
         export global Languages {{\n\
             out property <[string]> names: [\n\
         {names},\n\
             ];\n\
         }}\n"
    );

    fs::write(SLINT_OUT, slint).unwrap_or_else(|e| panic!("Could not write {SLINT_OUT}: {e}"));
}

/// Generates `translations.slint`, which exposes two globals:
///
/// - `TrKey`: one `int` constant per translation key (its index into `Tr.values`).
/// - `Tr`: a single `[string]` property holding the *current* language's strings,
///   in the same order as `TrKey`.
///
/// Compile-time defaults use English so the UI is never blank before the app
/// applies the user's actual language preference at startup. Switching languages
/// at runtime is then a single call that replaces the whole `Tr.values` array
/// (see `translations.rs`), which is far cheaper to maintain than one Slint
/// property per string.
///
/// `production/Langs/translations.json` must be an array of objects, each with
/// a `"key"` field and one field per language code from `lang-codes.json`
/// (e.g. `"en"`, `"tr"`, `"zh"`, `"es"`). `"en"` is required on every entry;
/// other language codes fall back to `"en"` with a build warning if missing.
fn generate_translations_slint() {
    const LANG_CODES_PATH: &str = "../../production/Langs/lang-codes.json";
    const JSON_PATH: &str = "../../production/Langs/translations.json";
    const SLINT_OUT: &str = "../../frontend/translations.slint";

    println!("cargo:rerun-if-changed={JSON_PATH}");
    println!("cargo:rerun-if-changed={LANG_CODES_PATH}");

    let lang_json = fs::read_to_string(LANG_CODES_PATH)
        .unwrap_or_else(|e| panic!("Could not read {LANG_CODES_PATH}: {e}"));
    let langs: Vec<serde_json::Value> = serde_json::from_str(&lang_json)
        .unwrap_or_else(|e| panic!("Invalid JSON in {LANG_CODES_PATH}: {e}"));
    let codes: Vec<&str> = langs
        .iter()
        .map(|l| {
            l["code"]
                .as_str()
                .unwrap_or_else(|| panic!("Missing \"code\" field in {LANG_CODES_PATH}"))
        })
        .collect();

    let json =
        fs::read_to_string(JSON_PATH).unwrap_or_else(|e| panic!("Could not read {JSON_PATH}: {e}"));
    let entries: Vec<serde_json::Value> =
        serde_json::from_str(&json).unwrap_or_else(|e| panic!("Invalid JSON in {JSON_PATH}: {e}"));

    let mut key_props = Vec::with_capacity(entries.len());
    let mut default_values = Vec::with_capacity(entries.len());

    for (index, entry) in entries.iter().enumerate() {
        let key = entry["key"]
            .as_str()
            .unwrap_or_else(|| panic!("Entry {index} in {JSON_PATH} is missing a \"key\" field"));

        let default_en = entry["en"].as_str().unwrap_or_else(|| {
            panic!("Entry \"{key}\" in {JSON_PATH} is missing its required \"en\" value")
        });

        for code in &codes {
            if *code != "en" && entry.get(*code).and_then(|v| v.as_str()).is_none() {
                println!(
                    "cargo:warning=translations.json: key \"{key}\" has no \"{code}\" value, falling back to \"en\""
                );
            }
        }

        key_props.push(format!(
            "    out property <int> {}: {index};",
            slintify_key(key)
        ));
        default_values.push(format!("        {default_en:?}"));
    }

    let slint = format!(
        "// AUTO-GENERATED BY BUILD.RS - DO NOT EDIT BY HAND!\n\
         // Edit production/Langs/translations.json instead!\n\
         \n\
         export global TrKey {{\n\
         {}\n\
         }}\n\
         \n\
         export global Tr {{\n\
             in property <[string]> values: [\n\
         {},\n\
             ];\n\
         }}\n",
        key_props.join("\n"),
        default_values.join(",\n"),
    );

    fs::write(SLINT_OUT, slint).unwrap_or_else(|e| panic!("Could not write {SLINT_OUT}: {e}"));
}

/// Writes a `slug -> png bytes` table for `production/assets/characters` into
/// `OUT_DIR`, so the icons ship inside the binary like every other asset
/// (nothing from `production/` is installed next to the executable).
///
/// Dropping a new `<character>.png` in that folder is all it takes to add one.
fn generate_character_icons() {
    const SOURCE: &str = "../../production/assets/characters";
    const PROCESSED: &str = "../../production/assets/processed/characters";
    const TABLE_HEADER: &str = "// AUTO-GENERATED BY BUILD.RS - DO NOT EDIT BY HAND!\n\
                                // Add a PNG to production/assets/characters instead!\n";
    const EMPTY_TABLE: &str = "// AUTO-GENERATED BY BUILD.RS - DO NOT EDIT BY HAND!\n\
                               // Add a PNG to production/assets/characters instead!\n\
                               pub static CHARACTER_ICONS: &[(&str, &[u8])] = &[];\n";

    println!("cargo:rerun-if-changed={SOURCE}");

    let out_path = Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR is not set"))
        .join("character_icons.rs");

    // `include_bytes!` resolves relative to the source file, so the table has
    // to spell out absolute paths.
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is not set");
    let repo_root = Path::new(&manifest_dir)
        .ancestors()
        .nth(2)
        .expect("the crate should live two levels below the repo root")
        .to_path_buf();

    // A checkout without the art still has to build; the cards just fall back
    // to the app logo.
    let processed = match fs::read_dir(PROCESSED) {
        Ok(processed) => processed,
        Err(e) => {
            println!(
                "cargo:warning=could not read {PROCESSED} ({e}); building without character icons"
            );
            fs::write(&out_path, EMPTY_TABLE)
                .unwrap_or_else(|e| panic!("Could not write {}: {e}", out_path.display()));
            return;
        }
    };

    let mut entries: Vec<(String, String)> = processed
        .filter_map(Result::ok)
        .filter_map(|entry| {
            let path = entry.path();
            if path.extension().and_then(|e| e.to_str()) != Some("png") {
                return None;
            }
            let name = path.file_name()?.to_str()?;
            let slug = path.file_stem()?.to_str()?.to_lowercase();
            let absolute = repo_root
                .join("production/assets/processed/characters")
                .join(name);
            Some((slug, absolute.to_str()?.to_string()))
        })
        .collect();
    entries.sort();

    if entries.is_empty() {
        println!("cargo:warning=no character icons found in {SOURCE}");
    }

    let rows = entries
        .iter()
        .map(|(slug, path)| format!("    ({slug:?}, include_bytes!({path:?})),"))
        .collect::<Vec<_>>()
        .join("\n");

    let generated =
        format!("{TABLE_HEADER}pub static CHARACTER_ICONS: &[(&str, &[u8])] = &[\n{rows}\n];\n");

    fs::write(&out_path, generated)
        .unwrap_or_else(|e| panic!("Could not write {}: {e}", out_path.display()));
}

fn slintify_key(key: &str) -> String {
    key.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_lowercase()
            } else {
                '-'
            }
        })
        .collect()
}

fn process_directory(root_source: &Path, current_source: &Path, target_base: &Path) {
    for entry in fs::read_dir(current_source).unwrap() {
        let entry = entry.unwrap();
        let path = entry.path();
        if path == target_base {
            continue;
        }

        let relative = path.strip_prefix(root_source).unwrap();
        let dest_path = target_base.join(relative);

        if path.is_dir() {
            fs::create_dir_all(&dest_path).unwrap();
            process_directory(root_source, &path, target_base);
        } else if path.is_file() {
            if let Some(extension) = path.extension().and_then(|os| os.to_str()) {
                let ext_lower = extension.to_lowercase();
                if ext_lower == "png" || ext_lower == "jpg" || ext_lower == "jpeg" {
                    let file_name = path.file_name().and_then(|os| os.to_str()).unwrap_or("");
                    if file_name.contains("background") {
                        fs::copy(&path, &dest_path).unwrap();
                        continue;
                    }

                    // Character icons fill a grid tile (~85px), the rest are
                    // small toolbar/status icons.
                    let size = if relative.starts_with("characters") {
                        128
                    } else {
                        64
                    };

                    if let Ok(img) = image::open(&path) {
                        let scaled = img.resize(size, size, FilterType::Lanczos3);
                        scaled
                            .save(&dest_path)
                            .expect("Failed to save downsampled asset");
                    } else {
                        fs::copy(&path, &dest_path).unwrap();
                    }
                }
            }
        }
    }
}
