[package]
name = "Aurora"
version = "2.0.0"
edition = "2021"
default-run = "Aurora"

[features]
default = ["beta"]
beta = []

[dependencies]
i-slint-backend-winit = { version = "1.17", default-features = false }
rfd = { version = "0.17", default-features = false, features = [
    "xdg-portal",
    "wayland",
] }
image = { version = "0.25", default-features = false, features = [
    "png",
    "jpeg",
    "webp",
] }
arboard = { version = "3", default-features = false, features = ["image-data"] }

backend = { path = "../backend" }
shared = { path = "../shared" }
ipc = { path = "../ipc" }

archive = { workspace = true }
open = { workspace = true }
slint = { workspace = true }
once_cell = { workspace = true }
log = { workspace = true }
rayon = { workspace = true }
twox-hash = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
dirs = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
reqwest = { workspace = true }
sysinfo = { workspace = true }
md5 = { workspace = true }

[build-dependencies]
slint-build = { workspace = true }
image = { workspace = true }
serde_json = { workspace = true }

[target.'cfg(target_os = "windows")'.build-dependencies]
winresource = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true }
mslnk = { workspace = true }
tray-icon = { version = "0.24.2", default-features = false }

[target.'cfg(target_os = "linux")'.dependencies]
libc = { workspace = true }

[lints.clippy]
enum_glob_use = "warn"
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
empty_structs_with_brackets = "warn"
rest_pat_in_fully_bound_structs = "warn"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
too_many_lines = "allow"
must_use_candidate = "allow"
wildcard_imports = "allow"
cast_precision_loss = "allow"
