[package]
name = "AuroraInstaller"
version = "2.0.0"
edition = "2024"

[[bin]]
name = "AuroraInstaller"
path = "src/main.rs"

[[bin]]
name = "AuroraUninstaller"
path = "src/uninstall/main.rs"

[dependencies]
rfd = { version = "0.17", default-features = false, features = [
    "xdg-portal",
    "wayland",
] }

shared = { path = "../shared", default-features = false }
ipc = { path = "../ipc" }

slint = { workspace = true }
open = { workspace = true }
dirs = { workspace = true }
anyhow = { workspace = true }
sysinfo = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
ureq = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true }

[build-dependencies]
slint-build = { workspace = true }

[target.'cfg(target_os = "windows")'.build-dependencies]
winresource = { workspace = true }
