[package]
name = "shared"
version = "2.0.0"
edition = "2021"

[features]
default = ["beta"]
beta = []

[dependencies]
display-info = "0.5"
env_logger = { version = "0.11", default-features = false }
env_filter = { version = "2.0.0", default-features = false, features = ["std"] }
termcolor = "1.4"
futures = { version = "0.3", default-features = false }
iana-time-zone = "0.1.65"
cpu_info = "=0.1.0"
unrar = { package = "unrar-ng", version = "0.7" }
zip = { version = "9.0.0-pre2", default-features = false, features = [
    "lzma",
    "deflate",
    "deflate64",
    "aes-crypto",
    "bzip2",
    "ppmd",
    "xz",
    "zstd",
] }

ipc = { path = "../ipc" }

archive = { workspace = true }
slint = { workspace = true }
anyhow = { workspace = true }
rayon = { workspace = true }
jwalk = { workspace = true }
log = { workspace = true }
dirs = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }
sysinfo = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
libc = { workspace = true }

[lints.clippy]
enum_glob_use = "warn"
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
empty_structs_with_brackets = "warn"
rest_pat_in_fully_bound_structs = "warn"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
too_many_lines = "allow"
must_use_candidate = "allow"
wildcard_imports = "allow"
